FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN bun install --frozen-lockfile

ARG DATABASE_URL="postgresql://postgres:mysecretpassword@localhost:5432/postgres"
RUN DATABASE_URL=${DATABASE_URL} bun run build
RUN cd packages/db && bunx prisma generate
EXPOSE 3000

CMD [ "bun","run","start:web" ]