FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

Copy ./apps/backend ./apps/backend

RUN bun install
RUN bun run db:migrate

EXPOSE 3002

CMD [ "bun","run","start:backend" ]

