

name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/todo-app-backend:${{ github.sha }}

      - name: SSH into server and deploy
        run: |
          run: |
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
            chmod 600 ~/ssh_key
            ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@52.90.154.152 << 'EOF'
            docker pull nishant0013thakur/todo-app-backend:${{ github.sha }}
            docker stop backend1 || true
            docker rm backend1 || true
            docker run --name backend1 -d -p 3002:3002 nishant0013thakur/todo-app-backend:${{ github.sha }}
          EOF
             